# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   ports:
#   - port: 8080
#   selector:
#     app: backend
#   clusterIP: None
apiVersion: v1
kind: Service
metadata:  
  name: api
spec:
  selector:    
    app: backend
  type: NodePort
  ports:  
  - name: http
    port: 8080
    nodePort: 30038
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: quay.io/amirhmi/jobunja_back:latest
        resources:
          requests:
            memory: "355Mi"
            cpu: "0.4"
          limits:
            cpu: "0.45"
            memory: "365Mi"
        ports:
        - containerPort: 8080